# Generated by Django 3.2 on 2021-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=60)),
                ('contact', models.CharField(db_column='Contact_No', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'None')], default='N', max_length=10)),
                ('roomtype', models.CharField(choices=[('DELLUXE ROOMS ( 200$ )', 'D'), ('JUNIOR SUITE ( 250$ )', 'J'), ('GRAND SUITE ( 300$ )', 'G')], default='D', max_length=100)),
                ('checkstatus', models.BooleanField(db_column='Checkin Status')),
                ('age', models.IntegerField(db_column='Age')),
                ('date_of_join', models.DateField(db_column='Date_Of_Join')),
                ('income', models.FloatField(db_column='income')),
                ('address', models.TextField(db_column='Address')),
                ('hotelImg', models.ImageField(db_column='Hotel_Img', upload_to='')),
            ],
        ),
    ]
