# Generated by Django 3.2 on 2021-04-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcheckin_register', '0002_alter_hotel_roomtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotelImg',
        ),
    ]
