# Generated by Django 3.2 on 2021-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcheckin_register', '0003_remove_hotel_hotelimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotelImg',
            field=models.ImageField(db_column='Image', null=True, upload_to=''),
        ),
    ]
