# Generated by Django 3.2.4 on 2021-09-27 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('bio', models.TextField(blank=True, max_length=250, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('social_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('social_insta', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
